### ISSUE TITLE
Failed to complete #converge action: [can't convert true into String]

### ISSUE THREAD

**Issue by ahelal** [RoboticCheese/kitchen-localhost#4]
Hi,

Thank your for your work. I just started using your driver. I am using it with the custom provisioner that we developed in house https://github.com/ahelal/kitchen-ansiblepush
I am not a ruby developer and I assume that's somehow its my fault. But just incase if you can have hints

Here is the stacktrace

```
D      [Localhost] #<Kitchen::Transport::Localhost::Connection:0x007fd8b28d79c0> (true)
D      [local command] BEGIN (true)
D      Cleaning up local sandbox in /tmp/default-macosx-1010-sandbox-20150624-35827-17n6w9r
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [can't convert true into String]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [can't convert true into String]
D      ---Nested Exception---
D      Class: TypeError
D      Message: can't convert true into String
D      ------Backtrace-------
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:338:in `exec'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:338:in `block in fork_subprocess'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:316:in `fork'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:93:in `run_command'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:259:in `run_command'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/shell_out.rb:68:in `run_command'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/kitchen-localhost-0.2.0/lib/kitchen/transport/localhost/connection.rb:47:in `block in execute'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/bundler-1.5.3/lib/bundler.rb:229:in `block in with_clean_env'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/bundler-1.5.3/lib/bundler.rb:216:in `with_original_env'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/bundler-1.5.3/lib/bundler.rb:222:in `with_clean_env'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/kitchen-localhost-0.2.0/lib/kitchen/transport/localhost/connection.rb:47:in `execute'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/provisioner/base.rb:70:in `block in call'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/transport/base.rb:79:in `initialize'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/kitchen-localhost-0.2.0/lib/kitchen/transport/localhost.rb:38:in `new'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/kitchen-localhost-0.2.0/lib/kitchen/transport/localhost.rb:38:in `connection'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/provisioner/base.rb:64:in `call'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:366:in `block in converge_action'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `call'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/atools/embedded/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:452:in `action'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:362:in `converge_action'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `each'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:138:in `converge'
D      /opt/atools/embedded/lib/ruby/gems/1.9.1/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `public_send'
D      /opt/atools/embedded/lib/
```

Cheers

**Comment by ahelal** [comment]
My bad, Since the provisioner works in push mode I had to return a string "true" in install_command and run_command. And that fixed the issue
Sorry :)
